<?php

/**
 * @file
 * Contains ignite_media methods.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\media\Entity\Media;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_media_ignite_demo_block() {
  $data = file_get_contents('https://source.unsplash.com/PhYq704ffdA/640x360');
  $file = \Drupal::service('file.repository')->writeData($data, 'public://media.jpg');
  $media = Media::create([
    'bundle' => 'image',
    'name' => 'Media Image',
    'field_image' => [
      'target_id' => $file->id(),
      'alt' => 'Media Image',
      'title' => 'Media Image',
    ],
  ]);

  $media->save();

  $block = BlockContent::create([
    'type' => 'media',
    'field_title' => 'Title Lorem Ipsum Dolor',
    'field_media' => [
      'target_id' => $media->id(),
    ],
  ]);

  $block->save();

  return $block;
}
