<?php

/**
 * @file
 * Contains ignite_embed methods.
 */

use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_embed_ignite_demo_block() {
  $block = BlockContent::create([
    'type' => 'embed',
    'field_title' => 'Lorem ipsum dolor sit',
    'field_script' => [
      'value' => '<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3304.2923446682735!2d-84.25801458463692!3d34.087650523310614!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88f57565534a5389%3A0x8862226a3f7a7225!2sMediacurrent!5e0!3m2!1sen!2sus!4v1662496761480!5m2!1sen!2sus" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
      'format' => 'full_html',
    ],
  ]);

  $block->save();

  return $block;
}
