<?php

/**
 * @file
 * Contains ignite_accordion methods.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_accordion_ignite_demo_block() {
  $block = BlockContent::create([
    'type' => 'accordion',
    'field_title' => 'Frequently Asked Questions',
  ]);

  $block->save();

  for ($i = 0; $i < 11; $i++) {
    $paragraph = Paragraph::create([
      'type' => 'accordion_item',
      'field_title' => 'Curabitur aliquet quam id dui posuere blandit.',
      'field_body' => [
        'format' => 'full_html',
        'summary' => '',
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.</p>',
      ],
    ]);

    $paragraph->save();

    $block->get('field_accordion_item')->appendItem($paragraph);
  }

  $block->save();

  return $block;
}
