<?php

/**
 * @file
 * Contains ignite_carousel methods.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_carousel_ignite_demo_block() {
  $data = file_get_contents('https://source.unsplash.com/PhYq704ffdA/640x360');
  $file = \Drupal::service('file.repository')->writeData($data, 'public://carousel.jpg');
  $media = Media::create([
    'bundle' => 'image',
    'name' => 'Carousel Image',
    'field_image' => [
      'target_id' => $file->id(),
      'alt' => 'Carousel Image',
      'title' => 'Carousel Image',
    ],
  ]);

  $media->save();

  $block = BlockContent::create([
    'type' => 'carousel',
    'field_title' => 'Title Lorem Ipsum Dolor',
  ]);

  for ($i = 0; $i < 6; $i++) {
    $paragraph = Paragraph::create([
      'type' => 'carousel_item',
      'field_title' => 'Curabitur aliquet quam',
      'field_summary' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.',
      'field_link' => [
        'uri' => 'https://www.drupal.org',
        'title' => 'Read more',
      ],
      'field_media' => [
        'target_id' => $media->id(),
      ],
    ]);

    $paragraph->save();

    $block->get('field_carousel_item')->appendItem($paragraph);
  }

  $block->save();

  return $block;
}
