<?php

/**
 * @file
 * Contains ignite_form methods.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\webform\Entity\Webform;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_form_ignite_demo_block() {
  $webform = Webform::load('contact');

  $block = BlockContent::create([
    'type' => 'form',
    'field_title' => 'Lorem ipsum dolor sit',
    'field_webform' => [
      'target_id' => $webform->id(),
    ],
  ]);

  $block->save();

  return $block;
}
