<?php

/**
 * @file
 * Contains ignite_block_quote methods.
 */

use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_block_quote_ignite_demo_block() {
  $data = file_get_contents('https://source.unsplash.com/MMJx78V7xS8/100x100');
  $file = \Drupal::service('file.repository')->writeData($data, 'public://quote.jpg');

  $block = BlockContent::create([
    'type' => 'quote',
    'field_quote' => 'Lorem ipsum urpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Luctus finibus erat nomunny!',
    'field_author' => 'Author Ipsum',
    'field_job_title' => 'My Job Title is Long, Mega Super Ultra Corporation',
  ]);

  $block->field_thumb->setValue([
    'target_id' => $file->id(),
    'alt' => 'Quote Image',
    'title' => 'Quote Image',
  ]);

  $block->save();

  return $block;
}
