<?php

/**
 * @file
 * Contains ignite_card_list methods.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\media\Entity\Media;
use Drupal\paragraphs\Entity\Paragraph;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_card_list_ignite_demo_block() {
  $block = BlockContent::create([
    'type' => 'card_list',
    'field_title' => 'Optional Section Title',
  ]);

  $block->save();

  $data = file_get_contents('https://source.unsplash.com/PhYq704ffdA/640x360');
  $file = \Drupal::service('file.repository')->writeData($data, 'public://card-item.jpg');
  $media = Media::create([
    'bundle' => 'image',
    'name' => 'Card Image',
    'field_image' => [
      'target_id' => $file->id(),
      'alt' => 'Card Image',
      'title' => 'Card Image',
    ],
  ]);
  $media->save();

  for ($i = 0; $i < 4; $i++) {
    $paragraph = Paragraph::create([
      'type' => 'card',
      'field_title' => 'Curabitur aliquet quam id dui posuere blandit.',
      'field_summary' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus auctor, turpis at luctus finibus, erat lectus convallis velit, at sodales purus lacus quis magna. Curabitur imperdiet sapien libero, fringilla ullamcorper nibh ullamcorper vitae. Proin sed luctus augue. Nam fringilla enim leo, non sodales ante gravida ac.',
      'field_link' => [
        'uri' => 'https://www.drupal.org',
        'title' => 'Read more',
      ],
      'field_media' => [
        'target_id' => $media->id(),
      ],
    ]);

    $paragraph->save();

    $block->get('field_card')->appendItem($paragraph);
  }

  $block->save();

  return $block;
}
