<?php

/**
 * @file
 * Contains ignite_teaser methods.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\media\Entity\Media;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_teaser_ignite_demo_block() {
  $data = file_get_contents('https://source.unsplash.com/PhYq704ffdA/640x360');
  $file = \Drupal::service('file.repository')->writeData($data, 'public://teaser.jpg');
  $media = Media::create([
    'bundle' => 'image',
    'name' => 'Teaser Image',
    'field_image' => [
      'target_id' => $file->id(),
      'alt' => 'Teaser Image',
      'title' => 'Teaser Image',
    ],
  ]);

  $media->save();

  $block = BlockContent::create([
    'type' => 'teaser',
    'field_title' => 'Title Lorem Ipsum Dolor',
    'field_eyebrow' => 'Eyebrow could be here',
    'field_link' => [
      'uri' => 'https://www.drupal.org',
      'title' => 'Learn more',
    ],
    'field_media' => [
      'target_id' => $media->id(),
    ],
    'field_summary' => 'Some sites need a tagline mauris ac dui sit amet sem facilisis finibus vitae et mi.',
    'field_teaser_layout' => 'left',
  ]);

  $block->save();

  return $block;
}
