<?php

/**
 * @file
 * Contains ignite_text methods.
 */

use Drupal\block_content\Entity\BlockContent;

/**
 * Implements hook_ignite_demo_block().
 */
function ignite_text_ignite_demo_block() {
  $block = BlockContent::create([
    'type' => 'text',
    'field_title' => 'Title Lorem Ipsum Dolor',
    'body' => [
      'value' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla vitae elit libero, a pharetra augue. Nullam quis risus eget urna mollis ornare vel eu leo. Nullam id dolor id nibh ultricies vehicula ut id elit. Donec ullamcorper nulla non metus auctor fringilla. Nullam id dolor id nibh ultricies vehicula ut id elit. Donec ullamcorper nulla non metus auctor fringilla.',
      'format' => 'basic_html',
    ],
  ]);

  $block->save();

  return $block;
}
